package fmshared.model;


import java.util.UUID;

import fmshared.fmrequest.RegisterRequest;

/** A class to store User information from the FMS database and use within the Java code
 *
 * @author TylorBayer
 */
public class Users extends FMSModel {

    /** Unique user name */
    private String userName;
    /** User's password */
    private String password;
    /** User's email address */
    private String email;
    /** User's first name */
    private String firstName;
    /** User's last name */
    private String lastName;
    /** User's gender */
    private String gender;
    /** User's unique personID assigned to the user's generated Person object */
    private String personID;


    /** Constructor for use within FMS
     *
     * @param userName Unique user name (non-empty string)
     * @param password User's password (non-empty string)
     * @param email User's email address (non-empty string)
     * @param firstName User's first name (non-empty string)
     * @param lastName User's last name (non-empty string)
     * @param gender User's gender ('m' or 'f')
     * @param personID User's unique personID generated by UUID (non-empty string)
     */
    public Users(String userName, String password, String email, String firstName, String lastName, String gender, String personID) {
        this.userName = userName;
        this.password = password;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.personID = personID;

        values.add(userName);
        values.add(password);
        values.add(email);
        values.add(firstName);
        values.add(lastName);
        values.add(gender);
        values.add(personID);
    }

    public Users(RegisterRequest regReq) {
        this.userName = regReq.getUserName();
        this.password = regReq.getPassword();
        this.email = regReq.getEmail();
        this.firstName = regReq.getFirstName();
        this.lastName = regReq.getLastName();
        this.gender = regReq.getGender();
        this.personID = UUID.randomUUID().toString();

        values.add(userName);
        values.add(password);
        values.add(email);
        values.add(firstName);
        values.add(lastName);
        values.add(gender);
        values.add(personID);
    }

    public void populateValues() {
        values.add(userName);
        values.add(password);
        values.add(email);
        values.add(firstName);
        values.add(lastName);
        values.add(gender);
        values.add(personID);
    }

    /** Constructor for GSON */
    public Users() {}
}
